<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entries [
<!ELEMENT entries (entry)>
<!ELEMENT entry (ord,var*,frase?,forkl+)>
<!ATTLIST entry id ID #REQUIRED>
<!ELEMENT ord (#PCDATA)>
<!ELEMENT forkl (#PCDATA|i)*>
<!ELEMENT frase (#PCDATA)>
<!ELEMENT var (#PCDATA)>
<!ELEMENT i (#PCDATA)>
]>

<!-- Online validator på http://www.stg.brown.edu/service/xmlvalid/ -->

<entries>

<entry id="aa">
 <ord>aa</ord>
 <forkl>(vb.; præt. aatte, aadte) ejer, ejede</forkl>
</entry>

<entry id="Abild">
 <ord>Abild</ord>
 <var>Abildtræ</var>
 <forkl>æbletræ; også: æble</forkl>
</entry>

<entry id="Abildgaard">
 <ord>Abildgaard</ord>
 <forkl>frugthave</forkl>
</entry>

<entry id="abildgraa">
 <ord>abildgraa</ord>
 <forkl>gråskimlet (om hest)</forkl>
</entry>

<entry id="Actæon">
 <ord>Actæon</ord>
 <forkl>en jæger som belurede den badende <xref ord="Diana"/>; hun forvandlede ham til en hjort, og hans egne hunde sønderrev ham</forkl>
</entry>

<entry id="Adonis">
 <ord>Adonis</ord>
 <forkl>i græsk mytologi en skøn yngling som elskes af <xref ord="Afrodite"/></forkl>
</entry>

<entry id="afhøre">
 <ord>afhøre</ord>
 <forkl>høre om</forkl>
</entry>

<entry id="afløse">
 <ord>afløse</ord>
 <forkl>give syndsforladelse, absolvere</forkl>
</entry>

<entry id="Afløsning">
 <ord>Afløsning</ord>
 <forkl>(sakramental) syndsforladelse, absolution</forkl>
</entry>

<entry id="Afrer">
 <ord>Afrer</ord>
 <forkl>afrikaner</forkl>
</entry>

<entry id="Afrodite">
 <ord>Afrodite</ord>
 <forkl>den græske gudinde for skønhed og kærlighed; svarer til den romerske Venus</forkl>
</entry>

<entry id="Aftenstjernen">
 <ord>Aftenstjernen</ord>
 <forkl>Venus, når den er synlig efter solnedgang</forkl>
</entry>

<entry id="Agent">
 <ord>Agent</ord>
 <forkl>en titel som kongen kunne tildele handelsmænd (grosserere)</forkl>
</entry>

<entry id="Agerrén">
 <ord>Agerrén</ord>
 <forkl>markskel; agerfure; plovfure</forkl>
</entry>

<entry id="Agonie">
 <ord>Agonie</ord>
 <forkl>dødskamp (egl.: væddekamp)</forkl>
</entry>

<entry id="Ahasverus">
 <ord>Ahasverus</ord>
 <forkl>gammeltestamentlig skikkelse; navn for den legendære 'Evige Jøde'</forkl>
</entry>

<entry id="alamodig">
 <ord>alamodig</ord>
 <forkl>alamodisk, moderne (af fr. <i>à la mode</i>)</forkl>
</entry>

<entry id="Albion">
 <ord>Albion</ord>
 <forkl>poetisk navn for England eller de britiske øer</forkl>
</entry>

<entry id="Album">
 <ord>Album</ord>
 <frase>Album amicorum</frase>
 <forkl>se Nøgleord <xref keyword="stambog"/></forkl>
</entry>

<entry id="Alfader">
 <ord>Alfader</ord>
 <var>Alfaudur</var>
 <forkl>navn for <xref ord="Odin"/>; også for de kristnes Gud</forkl>
</entry>

<entry id="Algodheds">
 <ord>Algodhed</ord>
 <forkl>navn for (de kristnes) Gud</forkl>
</entry>

<entry id="Allah">
 <ord>Allah</ord>
 <forkl>(den arabiske betegnelse for) Gud</forkl>
</entry>

<entry id="allegorisk">
 <ord>allegorisk</ord>
 <forkl>se Nøgleord <xref keyword="allegori"/></forkl>
</entry>

<entry id="Almagt">
 <ord>Almagt</ord>
 <forkl>om en af Guds egenskaber; også: den almægtige (Gud)</forkl>
</entry>

<entry id="Amazone">
 <ord>Amazone</ord>
 <forkl>medlem af et krigerisk folk af kvinder</forkl>
</entry>

<entry id="Amici">
 <ord>Amici</ord>
<forkl>
 venner (plur. af lat.
 <i>amicus</i>
 eller ital.
 <i>amico</i>)
 </forkl>
</entry>

<entry id="Anacreon">
 <ord>Anacreon</ord>
 <forkl>græsk lyriker, 500-tallet f.Kr.</forkl>
</entry>

<entry id="anbelange">
 <ord>anbelange</ord>
 <forkl>vedkomme, vedrøre, angå</forkl>
</entry>

<entry id="annamme">
 <ord>annamme</ord>
 <forkl>modtage; tilegne sig</forkl>
</entry>

<entry id="Ansvar">
 <ord>Ansvar</ord>
 <var>Ansuar</var>
<forkl>
 (i folkevise) svar (på spørgsmål) (sml. eng.
 <i>answer</i>
 )
 </forkl>
</entry>

<entry id="Antidot">
 <ord>Antidot</ord>
 <forkl>modgift</forkl>
</entry>

<entry id="Apollo">
 <ord>Apollo</ord>
 <var>Apol</var>
 <forkl>græsk gud for musik, for solen m.m.; personifikation af solen</forkl>
</entry>

<entry id="Apostat">
 <ord>Apostat</ord>
 <forkl>en frafalden, især: fra en religion</forkl>
</entry>

<entry id="Apotheose">
 <ord>Apotheose</ord>
 <forkl>ophøjelse til guddom</forkl>
</entry>

<entry id="Argelist">
 <ord>Argelist</ord>
 <forkl>træskhed, lumskhed</forkl>
</entry>

<entry id="Arhe">
 <ord>Arhe</ord>
 <forkl>åre (til at ro med)</forkl>
</entry>

<entry id="Arild">
 <ord>Arild</ord>
 <frase>fra Arilds Tid</frase>
 <forkl>fra de ældste tider; fra gammel tid; Arild er ikke et personnavn</forkl>
</entry>

<entry id="Arkipelag">
 <ord>Arkipelag</ord>
 <forkl>øhav</forkl>
</entry>

<entry id="Artemis">
 <ord>Artemis</ord>
 <forkl>græsk gudinde for jagten; svarer til den romerske Diana</forkl>
</entry>

<entry id="As">
 <ord>As</ord>
 <var>As-</var>
<forkl>
 en af de nordiske hovedguder; i sammensætninger:
 <i>As-,</i>
 f.eks.
 <i>Asa-Thor</i>
 </forkl>
</entry>

<entry id="Aseninde">
 <ord>Aseninde</ord>
 <forkl>hunæsel, æselhoppe</forkl>
</entry>

<entry id="Asgaard">
 <ord>Asgaard</ord>
 <forkl>asernes hjem</forkl>
</entry>

<entry id="Asgaardsrej">
 <ord>Asgaardsrej</ord>
 <forkl>flok af væsener der om natten rider støjende gennem luften</forkl>
</entry>

<entry id="Aske">
 <ord>Aske</ord>
 <forkl>(dødelige) mennesker</forkl>
</entry>

<entry id="Asynie">
 <ord>Asynie</ord>
 <forkl>gudinde hørende til aserne</forkl>
</entry>

<entry id="Attestats">
 <ord>Attestats</ord>
 <forkl>(teologisk) eksamen</forkl>
</entry>

<entry id="attisk">
 <ord>attisk</ord>
 <frase>attisk Salt</frase>
 <forkl>fint vid</forkl>
</entry>

<entry id="Attraa">
 <ord>Attraa</ord>
 <forkl>(stærkt) ønske, begær</forkl>
</entry>

<entry id="attraa2">
 <ord>attraa</ord>
 <var>adtraa</var>
 <forkl>ønske (stærkt), begære</forkl>
</entry>

<entry id="Aurora">
 <ord>Aurora</ord>
 <forkl>romersk gudinde; (personifikation af) morgenrøden</forkl>
</entry>

<entry id="Avind">
 <ord>Avind</ord>
 <var>Afvind</var>
 <forkl>misundelse, nid; had, fjendskab</forkl>
</entry>

<entry id="Avindskjold">
 <ord>Avindskjold</ord>
 <frase>bære Avindskjold mod Riget</frase>
 <forkl>kæmpe mod sit fædreland</forkl>
</entry>

<entry id="Avindsmand">
 <ord>Avindsmand</ord>
 <forkl>fjende</forkl>
</entry>

<entry id="Axel1">
 <ord>Axel</ord>
 <forkl>skulder</forkl>
</entry>

<entry id="Axel2">
 <ord>Axel</ord>
 <forkl>navn (næppe historisk) for Absalon (biskop, død <year>1201</year>)</forkl>
</entry>

<entry id="Axelstad">
 <ord>Axelstad</ord>
 <var>Axelhus</var>
 <var>Axelshavn</var>
 <forkl>poetisk navn for København</forkl>
</entry>

<entry id="axle">
 <ord>axle</ord>
 <var>aksle</var>
 <var>agsele</var>
 <var>achsele</var>
 <frase>axle sin Kaabe, sit Skind, osv.</frase>
 <forkl>stående udtryk i folkeviser: lægge kappen (osv.) på sin skulder; gøre sig rede til at gå ud; også: trække kappen bagom skuldrene for at vise at man er ubevæbnet, ikke har ondt i sinde</forkl>
</entry>

<entry id="baade">
 <ord>baade</ord>
 <forkl>gavne</forkl>
</entry>

<entry id="Baand">
 <ord>Baand</ord>
 <frase>Ridder af det hvide Baand</frase>
 <forkl>storkorsridder af Dannebrog</forkl>
</entry>

<entry id="Bacchant">
 <ord>Bacchant</ord>
 <forkl>bacchusdyrker, svirebroder</forkl>
</entry>

<entry id="Bacchantinde">
 <ord>Bacchantinde</ord>
 <forkl>bacchusdyrker, sviresøster</forkl>
</entry>

<entry id="Bacchus">
 <ord>Bacchus</ord>
 <var>Bacchi</var>
 <var>Bakkus</var>
 <var>Bakkos</var>
 <forkl>gen. <i>Bacchi</i>: romersk vingud; svarer til den græske <xref ord="Dionysos"/></forkl>
</entry>

<entry id="Bajadere">
 <ord>Bajadere</ord>
 <forkl>danserinde (egl. indisk tempeldanserinde)</forkl>
</entry>

<entry id="Ballade">
 <ord>Ballade</ord>
 <forkl>episk-lyrisk digt; romance</forkl>
</entry>

<entry id="bandsat">
 <ord>bandsat</ord>
 <forkl>(egl.) sat i band; (med afsvækket bet.) i høj grad; 'forfærdelig'</forkl>
</entry>

<entry id="Barcarole">
 <ord>Barcarole</ord>
 <var>Barkarole</var>
 <forkl>gondolsang, bådvise</forkl>
</entry>

<entry id="Barde">
 <ord>Barde</ord>
 <forkl>digter; skjald</forkl>
</entry>

<entry id="Basilisk">
 <ord>Basilisk</ord>
 <forkl>egl. 'lille konge'; fabeldyr hvis blik kan dræbe</forkl>
</entry>

<entry id="Bedemand">
 <ord>Bedemand</ord>
 <forkl>mand der mundtligt overbringer indbydelser, f.eks. til bryllupper</forkl>
</entry>

<entry id="Bedemandsstiil">
 <ord>Bedemandsstiil</ord>
 <forkl>vidtløftig, dunkel, uforståelig tale- eller skrivemåde</forkl>
</entry>

<entry id="befale">
 <ord>befale</ord>
 <forkl>overgive, overdrage, betro</forkl>
</entry>

<entry id="beføre">
 <ord>beføre</ord>
 <forkl>anklage, bagtale; vildlede, forlokke</forkl>
</entry>

<entry id="begegne">
 <ord>begegne</ord>
<forkl>
 tilstøde, hænde, vederfares (sml. ty.
 <i>begegnen</i>
 )
 </forkl>
</entry>

<entry id="behænde">
 <ord>behænde</ord>
 <forkl>behændig(t), flink(t); snild, listig</forkl>
</entry>

<entry id="belee">
 <ord>belee</ord>
 <forkl>le ad; gøre nar af</forkl>
</entry>

<entry id="Belial">
 <ord>Belial</ord>
 <forkl>navn for djævelen</forkl>
</entry>

<entry id="belyve">
 <ord>belyve</ord>
 <forkl>udsprede løgne om (en), bagvaske</forkl>
</entry>

<entry id="bert">
 <ord>bert</ord>
 <var>bjert</var>
 <forkl>bjert; lys, klar; skøn, fager</forkl>
</entry>

<entry id="beskære">
 <ord>beskære</ord>
<forkl>
 tildele, tilskikke, forunde (sml. ty.
 <i>bescheren</i>
 )
 </forkl>
</entry>

<entry id="bestedt">
 <ord>bestedt</ord>
 <var>bestæd</var>
 <forkl>som er i en vis stilling eller situation; stedt</forkl>
</entry>

<entry id="betee">
 <ord>betee</ord>
 <forkl>lægge for dagen; vise sig</forkl>
</entry>

<entry id="billig">
 <ord>billig</ord>
 <forkl>berettiget, rimelig</forkl>
</entry>

<entry id="Billing">
 <ord>Billing</ord>
 <forkl>lille stump, smule</forkl>
</entry>

<entry id="Bjærg1">
 <ord>Bjærg</ord>
 <forkl>skjul, gemme (ikke samme ord som <i>Bjerg</i>)</forkl>
</entry>

<entry id="Bjærg2">
 <ord>Bjærg</ord>
 <frase>Sol i Bjærge</frase>
 <forkl>solnedgang</forkl>
</entry>

<entry id="Blaamand">
 <ord>Blaamand</ord>
 <forkl>farvet person, 'morian'</forkl>
</entry>

<entry id="blank">
 <ord>blank</ord>
 <frase>de Blanke</frase>
<forkl>
 hvid (af race); denne bet. efter fr.
 <i>blanc</i>
 </forkl>
</entry>

<entry id="Blomme">
 <ord>Blomme</ord>
 <forkl>blomst</forkl>
</entry>

<entry id="Blomster">
 <ord>Blomster</ord>
<forkl>
 <i>et Blomster,</i>
 en blomst (efter norsk?)
 </forkl>
</entry>

<entry id="Blusemand">
 <ord>Blusemand</ord>
<forkl>
 revolutionær arbejder (efter fr.
 <i>blousier</i>
 )
 </forkl>
</entry>

<entry id="Blær">
 <ord>Blær</ord>
 <forkl>larm, ståhej; ufred; storm</forkl>
</entry>

<entry id="bold">
 <ord>bold</ord>
 <forkl>dristig, modig; ypperlig, skiøn</forkl>
</entry>

<entry id="Boreas">
 <ord>Boreas</ord>
 <forkl>poetisk: (personifikation af) nordenvinden</forkl>
</entry>

<entry id="Borg">
 <ord>Borg</ord>
 <forkl>kredit</forkl>
</entry>

<entry id="Borgeled">
 <ord>Borgeled</ord>
 <forkl>led eller låge ved indgangen til en borg</forkl>
</entry>

<entry id="braa">
 <ord>braa</ord>
 <forkl>hidsig</forkl>
</entry>

<entry id="Brad">
 <ord>Brad</ord>
 <var>Braad</var>
 <forkl>jagtbytte, steg (sml. 'mørbrad')</forkl>
</entry>

<entry id="brad2">
 <ord>brad</ord>
 <var>bradelig</var>
 <forkl>pludselig, uventet; hurtig</forkl>
</entry>

<entry id="bramarbaserende">
 <ord>bramarbaserende</ord>
 <forkl>storpralende</forkl>
</entry>

<entry id="bramme">
 <ord>bramme</ord>
 <forkl>prale, prange</forkl>
</entry>

<entry id="Bretland">
 <ord>Bretland</ord>
 <forkl>poetisk navn for Wales</forkl>
</entry>

<entry id="Bro">
 <ord>Bro</ord>
 <frase>Riber Bro, osv.</frase>
<forkl>
 brolagt vej eller gade; sml. <xref ord="Vesterbro"/></forkl>
</entry>

<entry id="Brod1">
 <ord>Brod1</ord>
 <forkl>spidst redskab, pigkæp; billedligt: 'dødens brod'</forkl>
</entry>

<entry id="Brod2">
 <ord>Brod2</ord>
 <var>Braad</var>
 <frase>en Braad i Hjærtet</frase>
 <forkl>billedligt; sml. 'dødens brod'</forkl>
</entry>

<entry id="Brog">
 <ord>Brog</ord>
 <forkl>bukser</forkl>
</entry>

<entry id="Brok">
 <ord>Brok</ord>
 <forkl>grævling</forkl>
</entry>

<entry id="brøste">
 <ord>brøste</ord>
 <forkl>svigte, mislykkes; udeblive, mangle</forkl>
</entry>

<entry id="brøstfældig">
 <ord>brøstfældig</ord>
 <var>brystfældig</var>
 <forkl>forfalden, skrøbelig</forkl>
</entry>

<entry id="Buur">
 <ord>Buur</ord>
 <var>Fruerbuur</var>
 <var>Jomfrubuur</var>
 <forkl>hus eller opholdsrum for (ugifte) kvinder</forkl>
</entry>

<entry id="Bycicle">
 <ord>Bycicle</ord>
 <forkl>(ellers sædvanligvis: <i>Bicycle</i>); cykel</forkl>
</entry>

<entry id="bygge">
 <ord>bygge</ord>
 <forkl>have sin bolig; bo</forkl>
</entry>

<entry id="böge">
 <ord>böge</ord>
 <forkl>(små)brøle (om ko)</forkl>
</entry>

<entry id="Camoene">
 <ord>Camoene</ord>
 <var>Kamøne</var>
 <forkl>kildenymfe; muse, sanggudinde</forkl>
</entry>

<entry id="Caprice">
 <ord>Caprice</ord>
 <var>Kaprice</var>
 <forkl>lune, indfald, grille</forkl>
</entry>

<entry id="Castellan">
 <ord>Castellan</ord>
 <forkl>borgfoged, slotsforvalter</forkl>
</entry>

<entry id="Cato">
 <ord>Cato</ord>
 <forkl>romersk statsmand (død 46 f.Kr.)</forkl>
</entry>

<entry id="Caudi">
 <ord>Caudi</ord>
 <frase>Peer Caudi</frase>
 <forkl>hånende betegnelse for student</forkl>
</entry>

<entry id="Ceres">
 <ord>Ceres</ord>
 <forkl>romersk gudinde for agerbrug</forkl>
</entry>

<entry id="Charis">
 <ord>Charis</ord>
 <var>Charite</var>
 <var>Kharite</var>
<forkl>
 græsk(e) gudinde(r) for skønhed og ynde; også navn på tidsskrift:
 <i>Charis</i>
 </forkl>
</entry>

<entry id="Charon">
 <ord>Charon</ord>
 <forkl>i græsk mytologi en færgemand der i underverdenen fragter de afdøde over floden <xref ord="Styx"/></forkl>
</entry>

<entry id="Cherub">
 <ord>Cherub</ord>
 <var>Cherubim</var>
 <forkl>(hebr. plur. <i>Cherubim</i>) engel; engel med flammesværd</forkl>
</entry>

<entry id="Chiddekel">
 <ord>Chiddekel</ord>
 <var>Hiddekel</var>
 <forkl>en af de fire paradisfloder <xref bibel="bibel1mose2,11-14"/></forkl>
</entry>

<entry id="Chloris">
 <ord>Chloris</ord>
 <forkl>græsk gudinde for vegetation og blomster; svarer til romernes Flora</forkl>
</entry>

<entry id="Christendommen">
 <ord>Christendommen</ord>
<forkl>
 kristenheden; den kristne verden (sml. eng.
 <i>Christendom</i>
 )
 </forkl>
</entry>

<entry id="Cimbrien">
 <ord>Cimbrien</ord>
 <var>Cimbrer</var>
 <var>cimbrisk</var>
 <forkl>poetisk (om) Jylland; også om hele Danmark</forkl>
</entry>

<entry id="Circe">
 <ord>Circe</ord>
 <forkl>en troldkvinde hvem <xref ord="Odysseus"/> besøgte og som forvandlede hans mænd til svin</forkl>
</entry>

<entry id="Colberger">
 <ord>Colberger-Hede</ord>
 <forkl>Kolberger Heide, et farvandsafsnit i Østersøen, benævnt efter en nærliggende hedestrækning</forkl>
</entry>

<entry id="Collats">
 <ord>Collats</ord>
 <var>Collaz</var>
 <forkl>gilde, kalas</forkl>
</entry>

<entry id="compotere">
 <ord>compotere</ord>
 <forkl>holde gilde, 'solde'</forkl>
</entry>

<entry id="Comtesse">
 <ord>Comtesse</ord>
 <forkl>en greves (ugifte) datter</forkl>
</entry>

<entry id="Concha">
 <ord>Concha</ord>
 <forkl>snegl; sneglehus; musling</forkl>
</entry>

<entry id="Confirmation">
 <ord>Confirmation</ord>
 <forkl>stadfæstelse</forkl>
</entry>

<entry id="Contenance">
 <ord>Contenance</ord>
 <forkl>fatning, selvbeherskelse</forkl>
</entry>

<entry id="Copist">
 <ord>Copist</ord>
 <forkl>1. kontorist; 2. en der kopierer, plagierer</forkl>
</entry>

<entry id="Corsaren">
 <ord>Corsaren</ord>
 <forkl>politisk-satirisk ugeblad, <year>1840</year>ff</forkl>
</entry>

<entry id="Creatur">
 <ord>Creatur</ord>
 <forkl>skabning</forkl>
</entry>

<entry id="Croesus">
 <ord>Croesus</ord>
 <forkl>konge i Lydien, berømt for sin rigdom</forkl>
</entry>

<entry id="Cypria">
 <ord>Cypria</ord>
 <frase>Venus Cypria</frase>
 <forkl>navn for Venus på Cypern</forkl>
</entry>

<entry id="Dagmoder">
 <ord>Dagmoder</ord>
 <var>Dagmoer</var>
 <forkl>poetisk navn for morgenrøden eller solen</forkl>
</entry>

<entry id="Dandser">
 <ord>Dandser</ord>
 <forkl>hest der er afrettet til at gøre dansetrin</forkl>
</entry>

<entry id="Dannebrogstegn">
 <ord>Dannebrogstegn</ord>
 <forkl>sølvkorset, den laveste grad i Dannebrogsordenen</forkl>
</entry>

<entry id="Dannemand">
 <ord>Dannemand</ord>
 <var>Dannermand</var>
 <forkl>agtværdig mand, hædersmand</forkl>
</entry>

<entry id="dannis">
 <ord>dannis</ord>
 <var>danis</var>
 <forkl>brav, hæderlig; høvisk; venlig</forkl>
</entry>

<entry id="Diana">
 <ord>Diana</ord>
 <forkl>romersk gudinde for jagten; svarer til den græske Artemis</forkl>
</entry>

<entry id="Dionysos">
 <ord>Dionysos</ord>
 <forkl>græsk vingud; svarer til den romerske Bacchus</forkl>
</entry>

<entry id="Dise">
 <ord>Dise</ord>
 <var>Dis</var>
 <var>Disse</var>
 <var>Diis</var>
 <var>Disa</var>
 <forkl>overnaturligt kvindeligt væsen; (poet.) gudinde; begrebet tilhører den norrøne forestillingsverden og kan også (poetisk) bruges om almindelige dødelige kvinder</forkl>
</entry>

<entry id="Doris">
 <ord>Doris</ord>
 <forkl>navn for diverse nereider m.v.</forkl>
</entry>

<entry id="dove">
 <ord>dove</ord>
 <forkl>blive sløv; lægge sig (om vind)</forkl>
</entry>

<entry id="Drapa">
 <ord>Drapa</ord>
 <forkl>oldnordisk digt med omkvæd</forkl>
</entry>

<entry id="Dreng">
 <ord>Dreng</ord>
 <forkl>(ung) mand; kriger</forkl>
</entry>

<entry id="Drot">
 <ord>Drot</ord>
 <forkl>konge</forkl>
</entry>

<entry id="Dryade">
 <ord>Dryade</ord>
 <var>Dryas</var>
 <forkl><xref ord="Nymphe"/> knyttet til et træ</forkl>
</entry>

<entry id="duftig">
 <ord>duftig</ord>
 <forkl>tåget, diset; ubestemt; virkelighedsfjern</forkl>
</entry>

<entry id="Dunstkreds">
 <ord>Dunstkreds</ord>
 <forkl>atmosfære</forkl>
</entry>

<entry id="dus">
 <ord>dus</ord>
 <forkl>dæmpet, sagte</forkl>
</entry>

<entry id="Dyrendal">
 <ord>Dyrendal</ord>
 <forkl>(stort) sværd; egl. navnet på Rolands sværd</forkl>
</entry>

<entry id="dædalisk">
 <ord>dædalisk</ord>
 <forkl>indviklet, sindrig</forkl>
</entry>

<entry id="Døn">
 <ord>Døn</ord>
 <forkl>drøn</forkl>
</entry>

<entry id="dønne">
 <ord>dønne</ord>
 <forkl>drøne</forkl>
</entry>

<entry id="Edom">
 <ord>Edom</ord>
 <forkl>Esau, patriarken Jakobs broder; folkestamme som anser sig for dennes efterslægt</forkl>
</entry>

<entry id="efterdi">
 <ord>efterdi</ord>
 <forkl>fordi, eftersom</forkl>
</entry>

<entry id="Eiland">
 <ord>Eiland</ord>
<forkl>
 øland, ø; sml. eng.
 <i>island</i>
 </forkl>
</entry>

<entry id="Elysium">
 <ord>Elysium</ord>
 <forkl>de saliges boliger i græsk mytologi</forkl>
</entry>

<entry id="enddog">
 <ord>enddog</ord>
 <forkl>endda</forkl>
</entry>

<entry id="endsige">
 <ord>endsige</ord>
 <forkl>(hvor) meget mere; for ikke at tale om (f.eks. <xref bibel="bibelordsprog15,11"/></forkl>
</entry>

<entry id="ephemer">
 <ord>ephemer</ord>
 <var>efemer</var>
 <forkl>døgnkort; forbigående; betydningsløs; også: døgnflue</forkl>
</entry>

<entry id="Erato">
 <ord>Erato</ord>
 <forkl><xref ord="Muse"/> for kærlighedslyrikken</forkl>
</entry>

<entry id="Erebus">
 <ord>Erebus</ord>
 <forkl>underverdenen i græsk mytologi</forkl>
</entry>

<entry id="Eriksgata">
 <ord>Eriksgata</ord>
 <forkl>egl. den nytiltrådte svenske konges rundrejse gennem riget</forkl>
</entry>

<entry id="erkjende">
 <ord>erkjende</ord>
 <forkl>anerkende</forkl>
</entry>

<entry id="Erkjendelse">
 <ord>Erkjendelse</ord>
 <forkl>anerkendelse</forkl>
</entry>

<entry id="erlange">
 <ord>erlange</ord>
<forkl>
 erhverve, opnå (efter ty.
 <i>erlangen</i>
 )
 </forkl>
</entry>

<entry id="Erycine">
 <ord>Erycine</ord>
 <frase>Venus Erycine</frase>
 <forkl>navn for Venus (efter bjerget Eryx på Sicilien)</forkl>
</entry>

<entry id="Eumenide">
 <ord>Eumenide</ord>
 <forkl>furie</forkl>
</entry>

<entry id="Euterpe">
 <ord>Euterpe</ord>
 <forkl><xref ord="Muse"/> for fløjtespil</forkl>
</entry>

<entry id="Evan">
 <ord>Evan</ord>
 <forkl>navn for <xref ord="Dionysos"/></forkl>
</entry>

<entry id="Extrapost">
 <ord>Extrapost</ord>
 <forkl>personbefordring som man mod særlig betaling kan bestille hos postvæsenet (til forskel fra den ordinære 'post' der følger en fast køreplan)</forkl>
</entry>

<entry id="fage">
 <ord>fage</ord>
<forkl>
 hastig, hurtig; hos Oehlenschläger (ved sammenblanding med
 <i><xref ord="fager"/></i>): smuk)
 </forkl>
</entry>

<entry id="fager">
 <ord>fager</ord>
 <var>favr</var>
 <var>fejr</var>
 <forkl>skøn, dejlig, yndig</forkl>
</entry>

<entry id="Falæner">
 <ord>Falæner</ord>
 <forkl>nat-sommerfugle</forkl>
</entry>

<entry id="Fang">
 <ord>Fang</ord>
 <forkl>favn; skød</forkl>
</entry>

<entry id="Farsot">
 <ord>Farsot</ord>
 <forkl>(alvorlig) epidemi</forkl>
</entry>

<entry id="fattes">
 <ord>fattes</ord>
 <forkl>mangle</forkl>
</entry>

<entry id="Fedel">
 <ord>Fedel</ord>
 <var>Fædel</var>
 <forkl>violin; violinlignende instrument</forkl>
</entry>

<entry id="Feldskiær">
 <ord>Feldskiær</ord>
 <var>Feltskær</var>
 <forkl>sårlæge, kirurg</forkl>
</entry>

<entry id="Feste">
 <ord>Feste</ord>
 <var>Fæste</var>
 <frase>Borg og Feste (pleonastisk)</frase>
 <forkl>befæstet sted; borg</forkl>
</entry>

<entry id="Fibel">
 <ord>Fibel</ord>
 <forkl>ABC; ABC-bog</forkl>
</entry>

<entry id="fige">
 <ord>fige</ord>
 <forkl>skynde sig, haste; stræbe, ivre, hige (efter), attrå</forkl>
</entry>

<entry id="Fimbulvinter">
 <ord>Fimbulvinter</ord>
 <forkl>(i nordisk mytologi) lang vinter forud for <xref ord="Ragnarok"/></forkl>
</entry>

<entry id="Fiskeskjær">
 <ord>Fiskeskjær</ord>
 <forkl>klippegrund i havet hvor der drives fiskeri</forkl>
</entry>

<entry id="fixere">
 <ord>fixere</ord>
 <var>fiksere</var>
 <forkl>have til bedste; narre</forkl>
</entry>

<entry id="Fjed">
 <ord>Fjed</ord>
 <forkl>skridt, trin</forkl>
</entry>

<entry id="fjæle">
 <ord>fjæle</ord>
 <forkl>skjule, dølge</forkl>
</entry>

<entry id="Flaccus">
 <ord>Flaccus</ord>
 <forkl>romersk digter; omtales ofte af Martial</forkl>
</entry>

<entry id="flak">
 <ord>flak</ord>
 <forkl>flad, jævn</forkl>
</entry>

<entry id="Flora">
 <ord>Flora</ord>
 <forkl>romersk gudinde for vegetation og blomster; svarer til den græske Chloris</forkl>
</entry>

<entry id="Flynder">
 <ord>Flynder</ord>
 <forkl>fladfisk; (om person) fjols</forkl>
</entry>

<entry id="Flæg">
 <ord>Flæg</ord>
 <forkl>(forskellige slags) vandplanter</forkl>
</entry>

<entry id="Fole">
 <ord>Fole</ord>
 <forkl>ung hest; føl; plag</forkl>
</entry>

<entry id="forblommet">
 <ord>forblommet</ord>
 <var>forblummet</var>
 <forkl>dunkel, utydelig; tvetydig</forkl>
</entry>

<entry id="Forbud">
 <ord>Forbud</ord>
 <forkl>forvarsel; bebudelse</forkl>
</entry>

<entry id="fordi">
 <ord>fordi</ord>
 <forkl>(i folkeviser) derfor</forkl>
</entry>

<entry id="fordrage">
 <ord>fordrage</ord>
 <forkl>udholde, tåle</forkl>
</entry>

<entry id="Fore">
 <ord>Fore</ord>
 <var>Forde</var>
 <forkl>adfærd, fremtræden</forkl>
</entry>

<entry id="forekomme">
 <ord>forekomme</ord>
 <forkl>komme i forkøbet</forkl>
</entry>

<entry id="forfare">
 <ord>forfare</ord>
 <forkl>gå til værks; bære sig ad</forkl>
</entry>

<entry id="forfaren">
 <ord>forfaren</ord>
 <forkl>erfaren, dreven</forkl>
</entry>

<entry id="Forfarenhed">
 <ord>Forfarenhed</ord>
 <forkl>erfaring</forkl>
</entry>

<entry id="forfængelig">
 <ord>forfængelig</ord>
 <forkl>indbildsk</forkl>
</entry>

<entry id="Forfængelighed">
 <ord>Forfængelighed</ord>
 <forkl>tomhed, tant; indbildskhed</forkl>
</entry>

<entry id="Forgemak">
 <ord>Forgemak</ord>
 <forkl>venteværelse for audienssøgende</forkl>
</entry>

<entry id="forgiette">
 <ord>forgiette</ord>
 <var>forgjætte</var>
 <var>forgætte</var>
<forkl>
 glemme (sml. eng.
 <i>forget</i>
 )
 </forkl>
</entry>

<entry id="forinden">
 <ord>forinden</ord>
 <forkl>indenfor</forkl>
</entry>

<entry id="Forliis">
 <ord>Forliis</ord>
 <forkl>tab</forkl>
</entry>

<entry id="Formue">
 <ord>Formue</ord>
 <forkl>evne</forkl>
</entry>

<entry id="fornemme">
 <ord>fornemme</ord>
 <var>fornam</var>
 <var>fornommen</var>
 <var>fornummet</var>
 <forkl>(præt. <i>fornam;</i> part. <i>fornommen, fornummet</i>) høre, få at vide, erfare; erkende</forkl>
</entry>

<entry id="fornumstig">
 <ord>fornumstig</ord>
 <forkl>fornuftig</forkl>
</entry>

<entry id="forraske">
 <ord>forraske</ord>
 <forkl>overraske</forkl>
</entry>

<entry id="Forretning">
 <ord>Forretning</ord>
 <forkl>om virksomhed i almindelighed (ikke blot handel); spec. om administration</forkl>
</entry>

<entry id="forsage">
 <ord>forsage</ord>
 <forkl>svigte</forkl>
</entry>

<entry id="forsand">
 <ord>forsand</ord>
 <forkl>i sandhed; virkelig</forkl>
</entry>

<entry id="fortryde">
 <ord>fortryde</ord>
 <forkl>fremkalde eller nære en følelse af ubehag; harmes, ærgre sig</forkl>
</entry>

<entry id="Fortuna">
 <ord>Fortuna</ord>
 <forkl>lykkens gudinde</forkl>
</entry>

<entry id="foruden">
 <ord>foruden</ord>
 <forkl>udenfor</forkl>
</entry>

<entry id="forvinde">
 <ord>forvinde</ord>
 <forkl>komme over; overstå</forkl>
</entry>

<entry id="forvorpen">
 <ord>forvorpen</ord>
 <forkl>ryggesløs, fræk</forkl>
</entry>

<entry id="fredsæl">
 <ord>fredsæl</ord>
 <forkl>fredselskende, fredelig</forkl>
</entry>

<entry id="Fredsælhed">
 <ord>Fredsælhed</ord>
 <forkl>det at være fredselskende</forkl>
</entry>

<entry id="Freya">
 <ord>Freya</ord>
 <var>Freia</var>
 <forkl>kærlighedens gudinde i nordisk mytologi</forkl>
</entry>

<entry id="Freya2">
 <ord>Freya</ord>
 <frase>Freyas Rok</frase>
 <forkl>stjernebilledet Orion</forkl>
</entry>

<entry id="Fridle">
 <ord>Fridle</ord>
 <var>Frille</var>
 <forkl>elskerinde</forkl>
</entry>

<entry id="friste">
 <ord>friste</ord>
 <frase>friste Livet</frase>
 <forkl>opholde livet (især: under vanskeligheder, farer, osv.)</forkl>
</entry>

<entry id="from">
 <ord>from</ord>
 <forkl>retskaffen, brav; sagtmodig, blid</forkl>
</entry>

<entry id="Fromme">
 <ord>Fromme</ord>
 <forkl>gavn, nytte, fordel</forkl>
</entry>

<entry id="Frue">
 <ord>Frue</ord>
 <forkl>indtil o. <year>1860</year> kun om en standspersons hustru; ellers: Madam(e)</forkl>
</entry>

<entry id="Frøken">
 <ord>Frøken</ord>
 <forkl>indtil o. <year>1860</year> kun om en standspersons datter; ellers: Jomfru(e); i middelalderen også om kongedatter</forkl>
</entry>

<entry id="fuld">
 <ord>fuld</ord>
<forkl>
 som adverbium med forstærkende betydning, eller blot udfyldende. Ofte sammenskrevet med det følgende ord; almindeligt hos Ingemann og Grundtvig. Alene fra denne sidstes
 <i>Nyaars-Morgen</i>
 (<year>1824</year>) er noteret følgende: <i>fuldbange, fuldbrat, fulddybt, fuldgammel, fuldgjerne, fuldgod, fuldhøie, fuldkjær, fuldklart, fuldkry, fuldlange, fuldliden, fuldliflig, fuldmange, fuldmørkt, fuldnær, fuldplat, fuldrappe, fuldrene, fuldrige, fuldsvare, fuldsær(t), fuldsød, fuldtaaget, fuldtør, fuldvarm, fuldværd</i>
 </forkl>
</entry>

<entry id="fus">
 <ord>fus</ord>
 <var>fuss</var>
 <forkl>ivrig, forhippet; hidsig, fremfusende</forkl>
</entry>

<entry id="Fylgie">
 <ord>Fylgie</ord>
 <forkl>værneånd</forkl>
</entry>

<entry id="Fylking">
 <ord>Fylking</ord>
 <forkl>slagorden; (opstillet) hær</forkl>
</entry>

<entry id="Fæstensøl">
 <ord>Fæstensøl</ord>
 <forkl>forlovelsesgilde (sml. <i>gravøl</i>)</forkl>
</entry>


<entry id="Galathe">
 <ord>Galathe</ord>
 <forkl>navn på en nereide</forkl>
</entry>

<entry id="Gallien">
 <ord>Gallien</ord>
 <forkl>poetisk navn for Frankrig</forkl>
</entry>

<entry id="Galpen">
 <ord>Galpen</ord>
 <forkl>råben; gispen</forkl>
</entry>

<entry id="Gam">
 <ord>Gam</ord>
 <forkl>grib; grif, drage (fabeldyr)</forkl>
</entry>

<entry id="Gammen">
 <ord>Gammen</ord>
 <forkl>glæde, morskab; skæmt</forkl>
</entry>

<entry id="Ganger">
 <ord>Ganger</ord>
 <forkl>(ædel) ridehest</forkl>
</entry>

<entry id="Ganymedes">
 <ord>Ganymed(es)</ord>
 <forkl>en skøn yngling som elskes af <xref ord="Zeus"/></forkl>
</entry>

<entry id="Gavler">
 <ord>Gavler</ord>
 <forkl>(planten) skvalderkål</forkl>
</entry>

<entry id="Gefion">
 <ord>Gefion</ord>
 <forkl>mytisk kvindelig skikkelse, knyttet til Sjælland</forkl>
</entry>

<entry id="Geni">
 <ord>Geni</ord>
 <forkl>(spøg.) med afsvækket bet.: anlæg, dygtighed</forkl>
</entry>

<entry id="Gestalt">
 <ord>Gestalt</ord>
 <forkl>udseende; skikkelse; form</forkl>
</entry>

<entry id="Gevalt">
 <ord>Gevalt</ord>
 <forkl>magt; vold; overlast</forkl>
</entry>

<entry id="Giefmild">
 <ord>Giefmild</ord>
 <forkl>gavmild</forkl>
</entry>

<entry id="Gige">
 <ord>Gige</ord>
<forkl>
 violin, violinlignende instrument (sml. ty.
 <i>Geige</i>
 )
 </forkl>
</entry>

<entry id="gild">
 <ord>gild</ord>
 <forkl>fortrinlig, ypperlig; prægtig; dygtig</forkl>
</entry>

<entry id="Gimle">
 <ord>Gimle</ord>
 <forkl>de saliges boliger efter <xref ord="Ragnarok"/></forkl>
</entry>

<entry id="Ginistan">
 <ord>Ginistan</ord>
<forkl>
 Ginnistan; et af ånder beboet fabelland (af. arab.
 <i>djinni,</i>
 plur.
 <i>djinn,</i> (ond) ånd, dæmon)
 </forkl>
</entry>

<entry id="Gisel">
 <ord>Gisel</ord>
 <forkl>strålekrans; glorie</forkl>
</entry>

<entry id="Gjallarhorn">
 <ord>Gjallarhorn</ord>
 <forkl><xref ord="Heimdal"/>s horn eller lur</forkl>
</entry>

<entry id="gjække">
 <ord>gjække</ord>
 <var>gecke</var>
 <var>gække</var>
 <forkl>narre, bedrage, vildlede</forkl>
</entry>

<entry id="Gladhjem">
 <ord>Gladhjem</ord>
 <forkl>navn på <xref ord="Odin"/>s bolig; egl. 'det strålende hjem'</forkl>
</entry>

<entry id="Glar">
 <ord>Glar</ord>
 <forkl>glas</forkl>
</entry>

<entry id="Glavind">
 <ord>Glavind</ord>
 <var>Glaffuend</var>
 <forkl>spyd; sværd</forkl>
</entry>

<entry id="Godike">
 <ord>Godike</ord>
 <forkl>Andr. Hart. Godiche (bogtrykker i Kbh. -<year>1763</year>-)</forkl>
</entry>

<entry id="Godtaar">
 <ord>Godtaar</ord>
<forkl>
 egl.
 <i>godt-Aar</i>
 ; senere opfattet som
 <i>god-Taar</i>
 ; drikkehilsen; skål
 </forkl>
</entry>

<entry id="Gothen">
 <ord>Gothen</ord>
 <forkl>(poet.) svenskeren, de svenske (egl.: person fra Götaland)</forkl>
</entry>

<entry id="graahærdet">
 <ord>graahærdet</ord>
 <forkl>gråhåret</forkl>
</entry>

<entry id="graaiset">